---
#
# SPDX-License-Identifier: GPL-3.0-or-later

stages:
  - check
  - build

check:
  before_script:
    # NOTE: Install latest archlinux-keyring before upgrading system. In the
    # future this should not be needed anymore when we can guarantee a valid
    # keyring for longer:
    # https://gitlab.archlinux.org/archlinux/archlinux-keyring/-/issues/4
    - pacman -Sy --needed --noconfirm archlinux-keyring
    - pacman --noconfirm -Syu --needed make shellcheck
  script:
    - make check
  stage: check
  interruptible: true

.build:
  artifacts:
    reports:
      metrics: output/metrics.txt
  before_script:
    - pacman -Sy --needed --noconfirm archlinux-keyring
    - pacman -Syu --needed --noconfirm arch-install-scripts bash dosfstools e2fsprogs erofs-utils gnupg grub jq libarchive libisoburn mtools openssl qemu-headless squashfs-tools zsync
  script:
    - ./.gitlab/ci/build_archiso.sh ${BUILD_SCRIPT_ARGS}
  stage: build
  tags:
    - vm

build_short:
  extends: .build
  parallel:
    matrix:
      - BUILD_SCRIPT_ARGS: ebaseline bootstrap
      - BUILD_SCRIPT_ARGS: desktop bootstrap
      - BUILD_SCRIPT_ARGS: ereleng bootstrap

build_long:
  extends: .build
  parallel:
    matrix:
      - BUILD_SCRIPT_ARGS: ebaseline iso
      - BUILD_SCRIPT_ARGS: desktop iso 
      - BUILD_SCRIPT_ARGS: ereleng iso
      - BUILD_SCRIPT_ARGS: ebaseline keys
      - BUILD_SCRIPT_ARGS: desktop keys
      - BUILD_SCRIPT_ARGS: ereleng keys
  tags:
    - fast-single-thread
